#!/bin/sh
# Preview script built for use with lf and fzf
LINES=30
case "$1" in
    *.png|*.jpg|*.jpeg) mediainfo "$1";;
    #*.mp4|*.mkv) echo "\n Audio \n" && ffprobe -v error -select_streams a:0 -show_entries "stream=codec_name,bit_rate,channels,sample_rate : format=duration" -of default=noprint_wrappers=1 '[CBM]_Code_Geass_-_Lelouch_of_the_Resurrection_[x265_10bit]_[138FC434].mkv' && echo "\n Video \n" && ffprobe -v error -select_streams v:0 -show_entries "stream=codec_name,bit_rate,display_aspect_ratio,pix_fmt,sample_rate,width,height : format=duration" -sexagesimal -of default=noprint_wrappers=1 "$1";;
        *.mp4|*.mkv) ffprobe -v error -select_streams v:0 -show_entries "stream=codec_name,bit_rate,display_aspect_ratio,pix_fmt,sample_rate,width,height : format=duration" -sexagesimal -of default=noprint_wrappers=1 "$1";;
    *.md) glow -s dark "$1";;
    *.pdf) pdftotext "$1" -;;
    *.zip) zipinfo "$1";;
    *.tar.gz) tar -ztvf "$1";;
    *.tar.bz2) tar -jtvf "$1";;
    *.tar) tar -tvf "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
    #*.html|*.xml) w3m -dump "$1";;
    *.zsh*|*.bash*|*.git*) pistol "$1";;
    *) highlight "$1" -O ansi --force;;
esac
